/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umgmemorygame.formularios;

import java.awt.Font;
import static java.util.concurrent.ThreadLocalRandom.current;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import umgmemorygame.controladores.LogicaJuego;
import umgmemorygame.controladores.Reproductor;

/**
 *
 * @author KORTIZ
 */
public class FrmBienvenida extends javax.swing.JFrame {

    JPanel p = new JPanel();
    JProgressBar b;
    JLabel cargando;
    private static Reproductor mi_reproductor;
    private static Thread tMusic;

    /**
     * Creates new form FrmBienvenida
     */
    public FrmBienvenida() {
        this.setTitle("Bienvenida");
        this.setSize(500, 400);
        this.setLocationRelativeTo(null);
        p.setLayout(null);
        this.getContentPane().add(p);

        JLabel saludo = new JLabel("Bienvenido");
        JLabel name = new JLabel("UMG Memory Game 1.0");
        saludo.setBounds(200, 60, 200, 40);
        saludo.setFont(new Font("Times New Roman", Font.PLAIN, 20));
        name.setBounds(150, 110, 200, 40);
        name.setFont(new Font("Times New Roman", Font.PLAIN, 20));
        p.add(name);
        p.add(saludo);

        b = new JProgressBar(0, 100);
        b.setBounds(100, 180, 300, 50);
        cargando = new JLabel();
        cargando.setBounds(210, 250, 200, 40);
        cargando.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        p.add(cargando);
        p.add(b);

        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                int value = 0;
                boolean stop = false;
                while (!stop) {
                    try {
                        if (value < 100) {
                            value += LogicaJuego.generateIntRandom(30);
                            if(value > 100){
                                value = 100;
                            }
                            b.setValue(value);
                            cargando.setText("Cargando " + value + "%...");
                            Thread.sleep(1000);
                        } else {
                            stop = true;
                            abrirMenu();
                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread t = new Thread(runnable);
        t.start();
    }

    private void abrirMenu() throws Exception{
        mi_reproductor.stop();
        tMusic.interrupt();
        FrmMenu menu = new FrmMenu();
        this.setVisible(false);
        menu.setVisible(true);
    }
    
    private static void reproducir() {
        while (true) {
            tMusic = new Thread(() -> {
                try {
                    mi_reproductor = new Reproductor();
                    mi_reproductor.AbrirFichero("src/umgmemorygame/musica/Bienvenida.mp3");
                    mi_reproductor.Play();
                    Thread.sleep(150000);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    System.out.println("Error: " + ex.getMessage());
                }
            });
            tMusic.run();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel1.setText("BIENVENIDA");

        jButton1.setText("Sguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)
                        .addGap(0, 154, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FrmJuego j = new FrmJuego();
        this.setVisible(false);
        j.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        Thread t = new Thread(() -> {
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FrmBienvenida().setVisible(true);
                }
            });
        });
        t.start();
        reproducir();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
