/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package umgmemorygame.formularios;

import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JPanel;
import umgmemorygame.controladores.LogicaJuego;
import umgmemorygame.util.Carta;

/**
 *
 * @author KORTIZ
 */
public class FrmJuego extends javax.swing.JFrame {

    /**
     * Creates new form FrmJuego
     */
    JPanel panel;
    JLabel matriz[][], fecha, cronometro, nombreJugador;
    public static int cont = 1, anterior = 0,xant,yant;

    public FrmJuego() {
        this.setTitle("Pantalla de juego");
        this.setSize(1000, 740);
        this.setLocationRelativeTo(null);
        pantallaJuego();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJuego().setVisible(true);
            }
        });
    }

    public void pantallaJuego() {
        panel = new JPanel();
        panel.setLayout(null);
        this.getContentPane().add(panel);

        JLabel saludo = new JLabel("UMG Memory Game 1.0");
        saludo.setBounds(110, 10, 300, 40);
        saludo.setFont(new Font("Times New Roman", Font.PLAIN, 20));
        panel.add(saludo);

        LogicaJuego l = new LogicaJuego();
        for (int i = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                LogicaJuego.matrizCartas[i][j] = new Carta(l.matriz1[i][j],i,j, new JLabel());
                LogicaJuego.matrizCartas[i][j].getVista().setBounds(380 + (j * 70), 10 + (i * 85), 70, 85);
                panel.add(LogicaJuego.matrizCartas[i][j].getVista());                
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
